Added one method listTransferMethods
hyperwallet/node-sdk pull request #50
Opened 2020-11-12 17:48 UTC by mpatel-hw-dev

Added one method listTransferMethods

2020-11-18 14:55 UTC, Rrathinasabapath approved these changes
Approving the changes. Ready to be reviewed by team onsite.

2020-11-18 19:49 UTC, arao6 requested changes
Pls resolve merge conflicts

2020-11-19 17:26 UTC, arao6 approved these changes

2020-11-19 18:04 UTC, vkorotchenko approved these changes

2020-11-19 18:41 UTC, merged